spring.application.name=foodSaver_App
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=foodsaver_app
spring.datasource.username=shreeprabha
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
